[tool.poetry]
name = "resubname"
version = "0.3.1"
description = "Rename subtitle filenames to match videos."
authors = ["Wu Haotian <whtsky@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/whtsky/resubname"
requires-poetry = ">=2.1,<3.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-cov = "^7.0.0"
ruff = "^0.16.4"

[build-system]
requires = ["poetry-core>=2.1.3,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
resubname = "resubname:cli"

[tool.ruff]
target-version = "py39"