on: push
name: Main workflow
jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    container: python:3.8

    steps:
      - uses: actions/checkout@v5
      - name: Check Python version
        run: |
          python -V
      - run: pip install "poetry>=2.1,<2.2"
      - run: poetry install
      - run: poetry run black --check .
  pytest:
    name: Test on ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container:
          - python:3.14
          - python:3.13
          - python:3.12
          - python:3.11
          - python:3.10
          - python:3.9
          - python:3.8
    steps:
      - uses: actions/checkout@v5
      - name: Check Python version
        run: |
          python -V
      - run: pip install "poetry>=2.1,<2.2"
      - run: poetry install
      - run: poetry run pytest --cov=resubname --cov-report xml --cov-report term-missing
      - uses: codecov/codecov-action@v6.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
